version: 2
sources:
- name: olist
  schema: "{{ env_var('ANALYSTOS_RAW_SCHEMA', 'raw') }}"
  tables:
  - name: customers
  - name: orders
  - name: order_items
  - name: products
  - name: sellers
  - name: payments
  - name: reviews
  - name: geolocation
  - name: product_category_translation
